export const keys = {
  PRELOADING_TIMEOUT: 3000,
}

export const dataUser = [
  {
    number: "80%",
    context:
      "of BaseBank's users actively utilize the swap feature for their crypto transactions.We collaborate as a collective of individuals bringing their whole self to a project and, together, create work that none of",
  },
  {
    number: "89%",
    context:
      "of BaseBank's users express high levels of satisfaction with the user interface",
  },
  {
    number: "10,000",
    context:
      "daily interactions on our community Telegram and Discord channels.",
  },
]
export const dataDapps1 = [
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
]

export const dataDapps3 = [
  {
    name: "Lending",
    USDT: 4000,
    BNB: 3800,
    ETH: 1490,
    BTC: 500,
    BBank: 500,
  },
  {
    name: "Borrowing",
    USDT: 4000,
    BNB: 3500,
    ETH: 1540,
    BTC: 500,
    BBank: 900,
  },
  {
    name: "Stake",
    USDT: 5000,
    BNB: 3600,
    ETH: 1460,
    BTC: 500,
    BBank: 800,
  },
  {
    name: "Swap",
    USDT: 4500,
    BNB: 3400,
    ETH: 1410,
    BTC: 500,
    BBank: 1200,
  },
  {
    name: "Mining",
    USDT: 4200,
    BNB: 3900,
    ETH: 1450,
    BTC: 500,
    BBank: 1600,
  },
  {
    name: "Lending",
    USDT: 4500,
    BNB: 2800,
    ETH: 2600,
    BTC: 550,
    BBank: 800,
  },
  {
    name: "Borrowing",
    USDT: 4100,
    BNB: 2400,
    ETH: 2700,
    BTC: 600,
    BBank: 1100,
  },
  {
    name: "Stake",
    USDT: 4300,
    BNB: 2700,
    ETH: 2500,
    BTC: 580,
    BBank: 750,
  },
  {
    name: "Swap",
    USDT: 4200,
    BNB: 2600,
    ETH: 2800,
    BTC: 570,
    BBank: 950,
  },
  {
    name: "Mining",
    USDT: 4400,
    BNB: 2900,
    ETH: 2700,
    BTC: 590,
    BBank: 850,
  },
  {
    name: "Lending",
    USDT: 3800,
    BNB: 2200,
    ETH: 2600,
    BTC: 600,
    BBank: 950,
  },
  {
    name: "Borrowing",
    USDT: 4200,
    BNB: 2400,
    ETH: 2700,
    BTC: 580,
    BBank: 1050,
  },
  {
    name: "Stake",
    USDT: 3900,
    BNB: 2100,
    ETH: 2500,
    BTC: 550,
    BBank: 850,
  },
  {
    name: "Swap",
    USDT: 4000,
    BNB: 2300,
    ETH: 2800,
    BTC: 590,
    BBank: 800,
  },
  {
    name: "Mining",
    USDT: 4100,
    BNB: 2600,
    ETH: 2700,
    BTC: 560,
    BBank: 900,
  },
]

export const dataDapps2 = [
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Lending",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Borrowing",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Stake",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Swap",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
  {
    name: "Mining",
    USDT: Math.floor(Math.random() * 5001),
    BNB: Math.floor(Math.random() * 5001),
    ETH: Math.floor(Math.random() * 5001),
    BTC: Math.floor(Math.random() * 5001),
    BBank: Math.floor(Math.random() * 5001),
  },
]

export const dataDapps4 = [
  {
    name: "Lending",
    USDT: 3829,
    BNB: 2356,
    ETH: 2210,
    BTC: 498,
    BBank: 1056,
  },
  {
    name: "Borrowing",
    USDT: 4156,
    BNB: 2289,
    ETH: 2523,
    BTC: 522,
    BBank: 1123,
  },
  {
    name: "Stake",
    USDT: 3978,
    BNB: 2201,
    ETH: 2376,
    BTC: 515,
    BBank: 1209,
  },
  {
    name: "Swap",
    USDT: 3890,
    BNB: 2410,
    ETH: 2305,
    BTC: 503,
    BBank: 1087,
  },
  {
    name: "Mining",
    USDT: 4023,
    BNB: 2333,
    ETH: 2489,
    BTC: 490,
    BBank: 1198,
  },
  {
    name: "Lending",
    USDT: 4300,
    BNB: 2700,
    ETH: 2600,
    BTC: 580,
    BBank: 950,
  },
  {
    name: "Borrowing",
    USDT: 3900,
    BNB: 2300,
    ETH: 2500,
    BTC: 600,
    BBank: 1050,
  },
  {
    name: "Stake",
    USDT: 4100,
    BNB: 2500,
    ETH: 2700,
    BTC: 560,
    BBank: 850,
  },
  {
    name: "Swap",
    USDT: 4200,
    BNB: 2600,
    ETH: 2800,
    BTC: 590,
    BBank: 800,
  },
  {
    name: "Mining",
    USDT: 4000,
    BNB: 2400,
    ETH: 2600,
    BTC: 570,
    BBank: 900,
  },
  {
    name: "Lending",
    USDT: 3700,
    BNB: 2200,
    ETH: 2600,
    BTC: 590,
    BBank: 950,
  },
  {
    name: "Borrowing",
    USDT: 4100,
    BNB: 2400,
    ETH: 2700,
    BTC: 600,
    BBank: 1050,
  },
  {
    name: "Stake",
    USDT: 3900,
    BNB: 2500,
    ETH: 2800,
    BTC: 580,
    BBank: 850,
  },
  {
    name: "Swap",
    USDT: 4200,
    BNB: 2600,
    ETH: 2700,
    BTC: 570,
    BBank: 800,
  },
  {
    name: "Mining",
    USDT: 4300,
    BNB: 2700,
    ETH: 2500,
    BTC: 560,
    BBank: 900,
  },
]
